# Generated by Django 2.1.2 on 2019-08-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasberrypy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='timeConfigure',
            field=models.IntegerField(default=30),
        ),
    ]
